name: detox_pro_dz
description: علاج إدمان الإنترنت - نسخة احترافية
version: 2.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  workmanager: ^0.5.1
  app_usage: ^4.0.1
  flutter_local_notifications: ^16.3.0
  purchases_flutter: ^6.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
